[project]
name = "detllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.14.0",
    "datasets>=5.0.1",
    "numpy>=2.2.6",
    "pytest>=9.1.1",
    "safetensors>=0.8.0",
    "torch>=2.13.0",
    "transformers>=5.14.1",
]

[project.scripts]
detllm = "detllm:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
